# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: postagain
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: postagain
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: postagain
  pool: 5
  timeout: 5000
